### ISSUE TITLE
Clarify timer format

### ISSUE THREAD

**Issue by Scoder12** [cooklang/spec#19]
The example seems to suggest that the timer uses a number, then %, then a time unit. Is this a strict requirement? What time formats are supported?

**Comment by dubadub** [comment]
>  Is this a strict requirement? 

No, it's not. I think I should mentions in conventions that if units weren't added then treat number as minutes (it will probably be 80% times like that). Leaving value empty is fine too, it will still generate a link to set timer but won't set any default value.

> What time formats are supported?

This is a good question. It should support any as soon as it's a number and units. There's a use-case to set a timer which has multiple units, f.e. `1 hour 40 mins` and in this case I expect to just use one units: `100 mins`.

As for units format, parser itself is agnostic to units. It's up to a CLI or app to understand and use them. A bit later we'll add unit conversion tables and based on these people can define any names for units and CLI still be able to understand. Saying that, now timers are used in iOS app and they expect standard name for units (minutes, hours) because we don't have these conversions tables yet.

**Comment by dubadub** [comment]
@Scoder12 I created a formal language description in [ENBF](https://github.com/cooklang/spec/blob/main/EBNF.md), hope it helps.

**Comment by Scoder12** [comment]
Awesome, it helps. I'm rewriting the rust parser by the way and just wanted to make sure I handle all the edge cases.

**Comment by dubadub** [comment]
@Scoder12 is that okay to close the issue?

**Comment by Scoder12** [comment]
Yep!
